# Change these first
owner: HighFlyDesigns # Your GitHub organization or username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Hosting Server
    url: $CWP_URL
    showAverageResponseTime: false
  - name: VPS Server
    url: $VPS_URL
    showAverageResponseTime: false

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.highflydesigns.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/HighFlyDesigns/status/master/assets/logo-notext.png
  name: High Fly Designs
  introTitle: "High Fly Designs is closing in 2023."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
